// All official UK cities (England, Scotland, Wales, Northern Ireland)
// plus major towns already selectable before. Sorted A–Z.
export const UK_CITIES = [
  "Aberdeen",
  "Armagh",
  "Bangor",
  "Bath",
  "Belfast",
  "Birmingham",
  "Bournemouth",
  "Bradford",
  "Brighton & Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Cardiff",
  "Carlisle",
  "Chelmsford",
  "Chester",
  "Chichester",
  "Colchester",
  "Coventry",
  "Derby",
  "Doncaster",
  "Dundee",
  "Dunfermline",
  "Durham",
  "Edinburgh",
  "Ely",
  "Exeter",
  "Glasgow",
  "Gloucester",
  "Hereford",
  "Hull",
  "Inverness",
  "Ipswich",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Lichfield",
  "Lincoln",
  "Lisburn",
  "Liverpool",
  "London",
  "Londonderry",
  "Luton",
  "Manchester",
  "Middlesbrough",
  "Milton Keynes",
  "Newcastle upon Tyne",
  "Newport",
  "Newry",
  "Northampton",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Perth",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Reading",
  "Ripon",
  "Salford",
  "Salisbury",
  "Sheffield",
  "Slough",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "St Asaph",
  "St Davids",
  "Stirling",
  "Stoke-on-Trent",
  "Sunderland",
  "Swansea",
  "Truro",
  "Wakefield",
  "Wells",
  "Westminster",
  "Winchester",
  "Wolverhampton",
  "Worcester",
  "Wrexham",
  "York",
  // Country-wide option, always last in the dropdown.
  "United Kingdom",
] as const;

export type UkCity = (typeof UK_CITIES)[number];
