export const UK_CITIES = [
  "Aberdeen",
  "Bath",
  "Belfast",
  "Birmingham",
  "Bournemouth",
  "Bradford",
  "Brighton & Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Cardiff",
  "Chester",
  "Coventry",
  "Derby",
  "Dundee",
  "Edinburgh",
  "Exeter",
  "Glasgow",
  "Hull",
  "Inverness",
  "Ipswich",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Liverpool",
  "London",
  "Londonderry",
  "Luton",
  "Manchester",
  "Middlesbrough",
  "Milton Keynes",
  "Newcastle upon Tyne",
  "Newport",
  "Northampton",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Reading",
  "Sheffield",
  "Slough",
  "Southampton",
  "Stirling",
  "Stoke-on-Trent",
  "Swansea",
  "United Kingdom",
  "Wolverhampton",
  "York",
] as const;

export type UkCity = (typeof UK_CITIES)[number];
